<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-F1663RVI" name="com.HerkoappTests.ValidateNewWindowTest" tests="5" failures="1" timestamp="12 Sep 2020 00:37:49 GMT" time="8.628" errors="0">
  <testcase name="clickOnOpenNewWindowlnk" time="5.084" classname="com.HerkoappTests.ValidateNewWindowTest"/>
  <testcase name="ValidateNewWindow" time="0.016" classname="com.HerkoappTests.ValidateNewWindowTest">
    <failure type="java.lang.AssertionError" message="expected [Test Page For Basic Ajax Example] but found [Windows Example Test]">
      <![CDATA[java.lang.AssertionError: expected [Test Page For Basic Ajax Example] but found [Windows Example Test]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.HerkoappTests.ValidateNewWindowTest.ValidateNewWindow(ValidateNewWindowTest.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- ValidateNewWindow -->
  <testcase name="launchWebSite" time="3.038" classname="com.HerkoappTests.ValidateNewWindowTest"/>
  <testcase name="clickOnNewWindow" time="0.474" classname="com.HerkoappTests.ValidateNewWindowTest"/>
  <testcase name="validateWebsite" time="0.016" classname="com.HerkoappTests.ValidateNewWindowTest"/>
</testsuite> <!-- com.HerkoappTests.ValidateNewWindowTest -->
